# Module: NumPy Assignments
## Lesson: NumPy

In [112]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np

# step 1- 5x5 ka ek random arr banate hai jisme 1 se 20 tak numbers honge
arr = np.random.randint(1,21,size=(5,5))

print("--- original array ---- ")
print(arr)

# step 2: Teesre column (Index 2) ke saare elements ko 1 se replace karte hain
# [:, 2] ka matlab -> ":" yani saari rows, aur "2" yani teesra column

# Numpy mein kisi hisse ko select karne ka tarika hota hai: [rows, columns]. Humein saari rows chahiye, isliye hum sirf colon : lagayenge. Aur humein teesra column chahiye, isliye hum index 2 lagayenge (Kyunki ginti 0 se shuru hoti hai: 0, 1, 2). arr[:, 2] = 1

arr[:, 2] = 1

print("\n--- Naya Array (3rd column ko 1 karne ke baad) ---")
print(arr)

--- original array ---- 
[[17  2 11  1 11]
 [12  3 13  6  6]
 [13  3  5 16  3]
 [19 18 20  7 13]
 [ 1 11 19 17  7]]

--- Naya Array (3rd column ko 1 karne ke baad) ---
[[17  2  1  1 11]
 [12  3  1  6  6]
 [13  3  1 16  3]
 [19 18  1  7 13]
 [ 1 11  1 17  7]]


In [113]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
reshape4x4= arr2.reshape(4,4)

diagonal = np.arange(0,17,4)
print(diagonal)

reshape4x4[[0,1,2,3],[0,1,2,3]] = 0

print(reshape4x4)


[ 0  4  8 12 16]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [114]:
# ### Assignment 2: Array Indexing and Slicing 
# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

numArr = np.arange(1,37).reshape((6,6))
slicingArr = numArr[2:5, 1:4]
print("-------------")
print(slicingArr)
print(numArr)


-------------
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [115]:
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr_1 = np.random.randint(1,26, size=(5,5))
print(arr_1)

top_row = arr_1[0,:]
bottom_row = arr_1[-1,:]
left_border= arr_1[1:-1, 0] # (Matlab row 1 se leke aakhiri ke pehle tak, aur 0th column)
right_border = arr_1[1:-1, -1]

borders = np.concatenate((top_row, bottom_row, left_border, right_border))

print('\nBorders:')
print(borders)


[[15 20 24 18 18]
 [16 23  9 22 20]
 [ 4 12 11 10 19]
 [10  1 24 18  2]
 [ 8  9 12  2 11]]

Borders:
[15 20 24 18 18  8  9 12  2 11 16  4 10 20 19  2]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [116]:
arr1 = np.random.randint(1,13, size=(3,4))
arr2 = np.random.randint(1,13, size=(3,4))

add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1 / arr2

print(add)
print(sub)
print(mul)
print(div)

[[15 16  7  5]
 [11 18  6 18]
 [11  9  3 14]]
[[-5  8  3  3]
 [-9 -4  2  6]
 [ 1 -1 -1 -2]]
[[50 48 10  4]
 [10 77  8 72]
 [30 20  2 48]]
[[0.5        3.         2.5        4.        ]
 [0.1        0.63636364 2.         2.        ]
 [1.2        0.8        0.5        0.75      ]]


In [117]:
arr = np.random.randint(1,17,size=(4,4))
print(arr)
print("\n")

print("----- ye row wise addition ------")
row_wise_sum = np.sum(arr, axis=1)
print(row_wise_sum)

print("\n")

print("---------ye col wise addition hai ---------")
col_wise_sum = np.sum(arr, axis=0)

print(col_wise_sum)



[[13 10  6  6]
 [11  3 16  4]
 [12 13 11  9]
 [ 3 16 15 14]]


----- ye row wise addition ------
[35 34 45 48]


---------ye col wise addition hai ---------
[39 42 48 33]


In [118]:
### Assignment 4: Statistical Operations


In [119]:
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr = np.arange(1,10).reshape(3,3)

# saare numbers ko jodo, phir unki count se divide karo
# [1, 2, 3, 4, 5] -> (1+2+3+4+5) / 5 = 3.0  ✅

mean = np.mean(arr)

# Mean nikalo, phir dekho ki har number mean se kitna door (door) hai — us door-i ka average hi Std Dev hai.
# Mean = 3 hai
# 1 kitna door hai? -> 3-1 = 2
# 3 kitna door hai? -> 3-3 = 0  (Mean se 0 door)
# 5 kitna door hai? -> 5-3 = 2
# Std Dev ≈ 1.4  (matlab average "door-i" hai ~1.4)

# Simple rule: Std Dev jitna bada → numbers mean se zyada bikhar e hue hain.

std = np.std(arr)

normalized_arr = (arr - mean) / std

print("Original: \n", arr)
print("\n Normalized:: \n", normalized_arr)



Original: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Normalized:: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [120]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

arr = np.random.randint(1,25, size=(5,5))

mean = arr.mean()
standard_dev = arr.std()
variant = arr.var()

print(mean, "\n", standard_dev, "\n", variant)

11.36 
 6.078684068118691 
 36.9504


In [121]:
### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

ran_int = np.random.randint(1,11, size=(3,3))
oned_arr = np.random.randint(1,11,size=(3,))
 
print("1D array: ", ran_int)
print("2D array: ", oned_arr)

result = ran_int + oned_arr

print("\n Result: \n", result)



1D array:  [[ 1  4  9]
 [ 1 10  7]
 [ 1  5  7]]
2D array:  [7 1 5]

 Result: 
 [[ 8  5 14]
 [ 8 11 12]
 [ 8  6 12]]


In [122]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr_2D = np.random.randint(1,12,size=(4,4))
print(arr_2D)
print("\n")
arr_1D = np.random.randint(1,11, size=(4,))
print(arr_1D)

# ab Column-wise karne ke liye 1D array ko "khada" (vertical) banana padta hai 'np.newaxis' se:
# [:, np.newaxis] se shape (4,) -> (4, 1) ban jaati hai
# arr[:, np.newaxis]
#     ↑      ↑
#   saari   naya dimension
#   values  column mein daal do
# : → "saare elements lo"
# , np.newaxis → "aur unhe ek column ki tarah khada kar do"

result = arr_2D - arr_1D[:, np.newaxis]
print("result: \n", result)




[[ 4  8  2  7]
 [ 4  4  8  9]
 [10  8 10  5]
 [10  1  5 10]]


[1 2 9 1]
result: 
 [[ 3  7  1  6]
 [ 2  2  6  7]
 [ 1 -1  1 -4]
 [ 9  0  4  9]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [123]:
#1
# matrix = np.arange(1,10).reshape(3,3)
# print(matrix)

# det = np.linalg.det(matrix)
# print(det)

# inverse = np.linalg.inv(matrix)
# print(inverse)

# eigenval = np.linalg.eigvals(matrix)
# print(eigenval)

# np.arange wali matrix use mat karo (1,2,3...9)
matrix = np.random.randint(1, 11, size=(3, 3))  # ✅ Isko use karo
print(matrix)
det = np.linalg.det(matrix)
print("Determinant:", det)
inverse = np.linalg.inv(matrix)
print("Inverse:\n", inverse)
eigenval = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenval)

[[ 7  7 10]
 [ 8  5  4]
 [ 8  8  8]]
Determinant: 72.0
Inverse:
 [[ 0.11111111  0.33333333 -0.30555556]
 [-0.44444444 -0.33333333  0.72222222]
 [ 0.33333333  0.         -0.29166667]]
Eigenvalues: [21.84466124+0.j         -0.92233062+1.56374745j -0.92233062-1.56374745j]


In [124]:
mat1 = np.random.randint(1,7, size=(2,3))
print(mat1)

print("\n")
mat2 = np.random.randint(1,7, size=(3,2))

print(mat2)
print("\n")
# matrix multiplication

product = np.dot(mat1, mat2)

print(product)

[[3 5 6]
 [6 3 2]]


[[1 1]
 [6 3]
 [2 2]]


[[45 30]
 [28 19]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [125]:
# q1
arr = np.arange(1, 10).reshape(3, 3)   # Step 1: (3,3) banao
print(arr)

arr_1x9 = arr.reshape(1, 9)             # Step 2: (1,9) banao
print(arr_1x9)

arr_9x1 = arr_1x9.reshape(9, 1)        # Step 3: (9,1) banao
print(arr_9x1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [126]:
#Q2

arr = np.random.randint(1,25,size=(5,5))
print(arr)
print("\n")

flatten = arr.flatten()
print(flatten)
print("\n")

print(flatten.reshape(5,5))

[[14 23 18  9 16]
 [15  3 16 17 12]
 [20 21  3  5 21]
 [20  5 17 11 16]
 [ 1 21  2  2 24]]


[14 23 18  9 16 15  3 16 17 12 20 21  3  5 21 20  5 17 11 16  1 21  2  2
 24]


[[14 23 18  9 16]
 [15  3 16 17 12]
 [20 21  3  5 21]
 [20  5 17 11 16]
 [ 1 21  2  2 24]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [127]:
arr = np.random.randint(1,26,size=(5,5))
print(arr, "\n")

# Numpy isko pair mein padhta hai — pehla pair (0,0), dusra (0,-1), teesra (-1,0), chautha (-1,-1):

corners = arr[[0,0,-1,-1], [0,-1,0,-1]]

print(corners)

[[ 3 21 20  8 18]
 [17 22 20 19  3]
 [ 1  2  4 25 14]
 [ 6 16 22  2  4]
 [16 22 21  2 16]] 

[ 3 18 16 16]


In [128]:
arr = np.random.randint(1,17,size=(4,4))
print(arr,"\n")
bool_index = arr[arr > 10] = 10

print(arr)

[[13 15  5  9]
 [10 12  4  1]
 [ 1  8  2 14]
 [ 5 10  5 13]] 

[[10 10  5  9]
 [10 10  4  1]
 [ 1  8  2 10]
 [ 5 10  5 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [129]:
#q1

data_type = [('name',"U10"), ("age","i4"), ('weights','f4')]

data = np.array([('Alice', 90, 55.5), ('Shub',45,55.5)], dtype=data_type)

data_order = np.sort(data, order='age')
print(data_order)

[('Shub', 45, 55.5) ('Alice', 90, 55.5)]


### Euclidean Distance kya hoti hai? Seedha bol toh — do points ke beech ki seedhi line ki length! School mein ye formula seekha tha:

Distance = √( (x2-x1)² + (y2-y1)² )
Example: Point A (1,2) aur Point B (4,6) ke beech:

Distance = √( (4-1)² + (6-2)² ) = √(9 + 16) = √25 = 5


In [130]:
data_types = [('x','i4'), ('y','i4')]
data = np.array([(1,2), (2,4)], dtype=data_types)

data['x'] # this gives all 'x' values like [1,2,3]
data['y'] #similarly gives y values

x_diff = data['x'][:, np.newaxis] - data['x']
y_diff = data['y'][:, np.newaxis] - data['y']

distance = np.sqrt(x_diff ** 2 + y_diff ** 2)

print(distance)



[[0.         2.23606798]
 [2.23606798 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [131]:
import numpy.ma as ma

normal_arr = np.random.randint(1,17,size=(4,4))
print(normal_arr, '\n')

customed_masked = ma.masked_greater(normal_arr, 10)
print(customed_masked, '\n')

print(customed_masked)

[[ 2 14  5  7]
 [ 1  4 11 14]
 [12  5  4  4]
 [14 12 15  2]] 

[[2 -- 5 7]
 [1 4 -- --]
 [-- 5 4 4]
 [-- -- -- 2]] 

[[2 -- 5 7]
 [1 4 -- --]
 [-- 5 4 4]
 [-- -- -- 2]]


In [133]:
arr = np.random.randint(1,10,size=(3,3))
print(arr, '\n')

hide_diagonals = ma.masked_array(arr, mask=np.eye(3))
print(hide_diagonals)

[[6 5 7]
 [9 5 5]
 [4 3 8]] 

[[-- 5 7]
 [9 -- 5]
 [4 3 --]]
