# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np

# step 1- 5x5 ka ek random arr banate hai jisme 1 se 20 tak numbers honge
arr = np.random.randint(1,21,size=(5,5))

print("--- original array ---- ")
print(arr)

# step 2: Teesre column (Index 2) ke saare elements ko 1 se replace karte hain
# [:, 2] ka matlab -> ":" yani saari rows, aur "2" yani teesra column

# Numpy mein kisi hisse ko select karne ka tarika hota hai: [rows, columns]. Humein saari rows chahiye, isliye hum sirf colon : lagayenge. Aur humein teesra column chahiye, isliye hum index 2 lagayenge (Kyunki ginti 0 se shuru hoti hai: 0, 1, 2). arr[:, 2] = 1

arr[:, 2] = 1

print("\n--- Naya Array (3rd column ko 1 karne ke baad) ---")
print(arr)

--- original array ---- 
[[17 14 14 16  4]
 [14  5  1 15 14]
 [19 17 19  6 14]
 [12  7  1 14 16]
 [19  8  5  1 14]]

--- Naya Array (3rd column ko 1 karne ke baad) ---
[[17 14  1 16  4]
 [14  5  1 15 14]
 [19 17  1  6 14]
 [12  7  1 14 16]
 [19  8  1  1 14]]


In [3]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
reshape4x4= arr2.reshape(4,4)

diagonal = np.arange(0,17,4)
print(diagonal)

reshape4x4[[0,1,2,3],[0,1,2,3]] = 0

print(reshape4x4)


[ 0  4  8 12 16]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [9]:
# ### Assignment 2: Array Indexing and Slicing 
# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

numArr = np.arange(1,37).reshape((6,6))
slicingArr = numArr[2:5, 1:4]
print("-------------")
print(slicingArr)
print(numArr)


-------------
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [21]:
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr_1 = np.random.randint(1,26, size=(5,5))
print(arr_1)

top_row = arr_1[0,:]
bottom_row = arr_1[-1,:]
left_border= arr_1[1:-1, 0] # (Matlab row 1 se leke aakhiri ke pehle tak, aur 0th column)
right_border = arr_1[1:-1, -1]

borders = np.concatenate((top_row, bottom_row, left_border, right_border))

print('\nBorders:')
print(borders)


[[ 3 10 14 24 20]
 [11 11 16  3  8]
 [10  7 24  6 12]
 [16 21 15 21 22]
 [21 11  7  6 13]]

Borders:
[ 3 10 14 24 20 21 11  7  6 13 11 10 16  8 12 22]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [24]:
arr1 = np.random.randint(1,13, size=(3,4))
arr2 = np.random.randint(1,13, size=(3,4))

add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1 / arr2

print(add)
print(sub)
print(mul)
print(div)

[[15 18 10  7]
 [12 17  4  6]
 [15  2 10 18]]
[[ 7  4  0  3]
 [-4 -3  2 -4]
 [-7  0 -8 -6]]
[[44 77 25 10]
 [32 70  3  5]
 [44  1  9 72]]
[[2.75       1.57142857 1.         2.5       ]
 [0.5        0.7        3.         0.2       ]
 [0.36363636 1.         0.11111111 0.5       ]]


In [36]:
arr = np.random.randint(1,17,size=(4,4))
print(arr)
print("\n")

print("----- ye row wise addition ------")
row_wise_sum = np.sum(arr, axis=1)
print(row_wise_sum)

print("\n")

print("---------ye col wise addition hai ---------")
col_wise_sum = np.sum(arr, axis=0)

print(col_wise_sum)



[[ 5  7  7  8]
 [ 4 10  2 11]
 [12 12 13 16]
 [12 12  4 11]]


----- ye row wise addition ------
[27 27 53 39]


---------ye col wise addition hai ---------
[33 41 26 46]


In [ ]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
